#!/bin/bash
# /* -*-  indent-tabs-mode:t; tab-width: 8; c-basic-offset: 8  -*- */
# /*
# Copyright (c) 2014, Daniel M. Lofaro <dan (at) danLofaro (dot) com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the author nor the names of its contributors may
#       be used to endorse or promote products derived from this software
#       without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# */
# Daniel M. Lofaro (dan@danlofaro.com)

export LD_LIBRARY_PATH=/usr/lib:
ROBOT_PATH_MAIN=$('pwd')

CONTROLLER_REF_CHAN='controller-ref-chan'

MakeAch()
{
	ach -1 -C $CONTROLLER_REF_CHAN -m 30 -n 3000000
        sudo chmod 777 /dev/shm/achshm-*
}

Run()
{
     MakeAch
     ./controller-c
}

KillRemote()
{
	sudo kill -9 $(pidof achd)
}

KillAll()
{
	KillRemote
        sudo kill -9 $(pidof controller-c)
        sudo rm -r /dev/shm/achshm*
}


echo '======================================'
echo '========= Controller Example ========='
echo '========== Daniel M. Lofaro =========='
echo '========= dan@danLofaro.com =========='
echo '======================================'


## Start all other parts ##
case "$1" in
	'run' )
		Run
	;;
	'make' )
		MakeAch
	;;
	'kill' )
		KillAll
	;;
	*)
		echo 'run, make, or kill'
		exit 1
	;;
esac

exit 0

# Local Variables:
#  indent-tabs-mode:t
#  tab-width: 8
#  c-basic-offset: 8
# End:
